# Data Encoding – Nominal (One-Hot Encoding)

---

# 1. What is Data Encoding?

**Data Encoding** is the process of converting **categorical (text) data into numerical values** so that machine learning algorithms can understand and process it.

Machine learning models work with numbers, not text.

For example:

| Color |
| ----- |
| Red   |
| Blue  |
| Green |

A machine learning algorithm cannot directly process `"Red"` or `"Blue"`. These values must first be converted into numbers through **encoding**.

---

# 2. Why do Machine Learning Models Need Numerical Data?

Most ML algorithms perform mathematical operations such as:

* Distance calculation (KNN, K-Means)
* Dot products (Linear Regression, Logistic Regression)
* Matrix multiplication (Neural Networks)
* Gradient Descent
* Probability calculations

Text values cannot participate in these computations.

Example:

```text
Color

Red
Blue
Green
```

The algorithm cannot compute:

```text
Red + Blue = ?
```

After encoding:

```text
Red   → 1
Blue  → 2
Green → 3
```

Now numerical operations become possible (though this particular encoding is only appropriate in some cases).

---

# 3. What Problem Does Data Encoding Solve?

Without encoding:

```text
City

Delhi
Mumbai
Kolkata
```

Most machine learning algorithms will produce an error because they expect numeric input.

Data encoding solves:

* Inability to train models on text features.
* Conversion of categorical variables into machine-readable form.
* Better representation of categorical relationships.

---

# 4. When Should I Use Data Encoding?

Use data encoding whenever your dataset contains **categorical features**.

Examples:

| Feature    | Type        |
| ---------- | ----------- |
| Gender     | Categorical |
| City       | Categorical |
| Education  | Categorical |
| Color      | Categorical |
| Department | Categorical |

---

# 5. When Should I NOT Use Data Encoding?

* Do **not** encode the **target variable** using One-Hot Encoding for standard classification tasks. Use Label Encoding or let the library handle class labels.
* Do **not** apply One-Hot Encoding to numerical features.
* Avoid One-Hot Encoding when a feature has **thousands of unique categories (high cardinality)** because it creates too many columns.
* Do **not** fit the encoder on the entire dataset before splitting into train and test sets (data leakage).

---

# 6. Types of Data Encoding

## A. Label Encoding

Converts each category into an integer.

Example:

| Color | Encoded |
| ----- | ------- |
| Red   | 0       |
| Blue  | 1       |
| Green | 2       |

**Best for:** Ordinal data or target labels.

---

## B. Ordinal Encoding

Used when categories have a natural order.

Example:

| Size   | Encoded |
| ------ | ------- |
| Small  | 1       |
| Medium | 2       |
| Large  | 3       |

---

## C. One-Hot Encoding (OHE)

Creates a separate binary column for every category.

Example:

| Color |
| ----- |
| Red   |
| Blue  |
| Green |

↓

| Red | Blue | Green |
| --: | ---: | ----: |
|   1 |    0 |     0 |
|   0 |    1 |     0 |
|   0 |    0 |     1 |

---

## D. Binary Encoding

Converts categories to binary numbers.

Useful for high-cardinality features.

---

## E. Frequency Encoding

Replaces categories with their frequency.

Example:

| City   | Count |
| ------ | ----: |
| Delhi  |   120 |
| Mumbai |    80 |

---

## F. Count Encoding

Similar to frequency encoding but uses raw counts.

---

## G. Target Encoding

Encodes each category using the average value of the target.

Often useful for high-cardinality features but must be used carefully to avoid leakage.

---

## H. Hash Encoding

Uses a hash function to map categories into a fixed number of columns.

Common in very large datasets.

---

# 7. Types of Categorical Variables

Understanding the type of categorical variable is essential because it determines the correct encoding technique.

## A. Nominal Data

No natural order.

Examples:

| Feature     | Values                 |
| ----------- | ---------------------- |
| Color       | Red, Blue, Green       |
| City        | Delhi, Mumbai, Kolkata |
| Country     | India, USA, Japan      |
| Blood Group | A, B, AB, O            |

Correct encoding:

✅ One-Hot Encoding

---

## B. Ordinal Data

Categories have a meaningful order.

Examples:

| Feature   | Values                                    |
| --------- | ----------------------------------------- |
| Education | High School → Bachelor's → Master's → PhD |
| Rating    | Poor → Fair → Good → Excellent            |
| Size      | Small → Medium → Large                    |

Correct encoding:

✅ Ordinal Encoding

---

# Deep Dive into Nominal Data

---

## What is Nominal Data?

Nominal data consists of categories **without any inherent order or ranking**.

Example:

```text
Apple

Banana

Orange
```

Question:

Is Apple greater than Banana?

No.

There is **no mathematical relationship** between these categories.

---

## Examples

### Gender

Male

Female

Other

---

### City

Delhi

Mumbai

Kolkata

Chennai

---

### Blood Group

A

B

AB

O

---

### Car Brand

BMW

Audi

Toyota

Tesla

---

# Why Can't We Use Label Encoding for Nominal Data?

Suppose:

```text
Red   → 0

Blue  → 1

Green → 2
```

The model may incorrectly assume:

```text
Green > Blue > Red
```

But colors have **no order**.

This introduces a **false relationship**.

Therefore:

❌ Label Encoding

✅ One-Hot Encoding

---

# One-Hot Encoding (OHE)

## Definition

One-Hot Encoding converts each category into a **new binary feature**.

Each row has:

* 1 → Category is present.
* 0 → Category is absent.

---

## Example

Original:

| Color |
| ----- |
| Red   |
| Blue  |
| Green |
| Red   |

After OHE:

| Red | Blue | Green |
| --: | ---: | ----: |
|   1 |    0 |     0 |
|   0 |    1 |     0 |
|   0 |    0 |     1 |
|   1 |    0 |     0 |

---

# How Does One-Hot Encoding Work?

Suppose there are **k** unique categories.

OHE creates **k new columns**.

Example:

```text
Color

Red

Blue

Green
```

↓

```text
Red

Blue

Green
```

↓

```text
Red Blue Green

1    0    0

0    1    0

0    0    1
```

Each row contains exactly one **1**.

---

# Dummy Variable Trap

Suppose:

| Red | Blue | Green |
| --: | ---: | ----: |
|   1 |    0 |     0 |
|   0 |    1 |     0 |
|   0 |    0 |     1 |

Notice:

```text
Red + Blue + Green = 1
```

One column can always be inferred from the others.

This creates **perfect multicollinearity**, known as the **Dummy Variable Trap**.

Solution:

Drop one column.

Example:

| Blue | Green |
| ---: | ----: |
|    0 |     0 |
|    1 |     0 |
|    0 |     1 |

Here, `Red` is implied when both remaining columns are 0.

> This matters mainly for linear models such as Linear Regression and Logistic Regression. Tree-based models usually don't require dropping a column.

---

# Mathematical Representation

Suppose

Categories

```text
A

B

C
```

Vectors

```text
A = (1,0,0)

B = (0,1,0)

C = (0,0,1)
```

These vectors are orthogonal.

Their dot product is zero.

Meaning:

The categories remain completely independent.

---

# Code

## Using Pandas

```python
import pandas as pd

df = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Red"]
})

encoded = pd.get_dummies(df, columns=["Color"])

print(encoded)
```

Output:

```text
   Color_Blue  Color_Green  Color_Red
0           0            0          1
1           1            0          0
2           0            1          0
3           0            0          1
```

---

## Using Scikit-learn

```python
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(
    sparse_output=False,
    handle_unknown="ignore"
)

encoded = encoder.fit_transform(df[["Color"]])
```

> **Important:** Fit the encoder on the training data only, then use `transform()` on validation and test data.

---

# Pros

* No false ordering.
* Works well for nominal variables.
* Easy to interpret.
* Supported by almost every ML library.
* Suitable for most classification and regression problems.

---

# Cons

* Creates many new columns.
* Memory usage increases.
* Not suitable for high-cardinality features.
* Can slow training when there are many categories.

---

# Algorithm Compatibility

| Algorithm           | OHE Recommended?                                               |
| ------------------- | -------------------------------------------------------------- |
| Linear Regression   | ✅                                                              |
| Logistic Regression | ✅                                                              |
| KNN                 | ✅                                                              |
| SVM                 | ✅                                                              |
| Neural Networks     | ✅                                                              |
| Naive Bayes         | ✅                                                              |
| Decision Tree       | ⚠️ Optional                                                    |
| Random Forest       | ⚠️ Optional                                                    |
| XGBoost             | ⚠️ Optional                                                    |
| LightGBM            | ⚠️ Optional                                                    |
| CatBoost            | ❌ Usually not needed (handles categorical features internally) |

---

# Decision Flow

```text
Categorical Feature?

│

├── No

│      ▼

Use Directly

│

└── Yes

       │

       ▼

Ordered?

├── Yes

│      ▼

Ordinal Encoding

│

└── No

       │

       ▼

Number of Categories?

├── Few (<10–20)

│      ▼

One-Hot Encoding

│

└── Many

       ▼

Frequency / Target / Hash / Binary Encoding
```

---

# Interview Questions

### Basic

* What is One-Hot Encoding?
* Why do we encode categorical variables?
* What is nominal data?

### Intermediate

* Difference between Label Encoding and One-Hot Encoding?
* What is the Dummy Variable Trap?
* When should you use `drop='first'`?

### Advanced

* How does `handle_unknown="ignore"` work?
* What problems arise with high-cardinality features?
* When would you choose Target Encoding instead of One-Hot Encoding?

---

# Common Mistakes

❌ Using Label Encoding for nominal features.

❌ Applying OHE before train-test splitting.

❌ Forgetting to handle unseen categories in the test set.

❌ Using OHE for features with thousands of unique values.

❌ Dropping columns without understanding whether the chosen model requires it.

---

# Real-World Examples

### E-commerce

Product category:

* Electronics
* Clothing
* Books

Use One-Hot Encoding before training a recommendation model.

---

### Banking

Account type:

* Savings
* Current
* Salary

Encode account type as binary columns.

---

### Healthcare

Blood group:

* A
* B
* AB
* O

Since blood groups have no order, use One-Hot Encoding.

---

### Ride-Sharing

Payment method:

* Cash
* Card
* UPI
* Wallet

Represent each payment method with its own binary feature.

---

### Movie Recommendation

Genre:

* Action
* Comedy
* Drama

Encode genres for recommendation and prediction models.

---

# Revision Box

```text
Data Encoding

Purpose:
✔ Convert categorical data into numbers

Nominal Data:
✔ No order
✔ Use One-Hot Encoding

Ordinal Data:
✔ Has order
✔ Use Ordinal Encoding

One-Hot Encoding:
✔ One binary column per category
✔ Avoids false ordering
✔ Good for low-cardinality features

Avoid:
✘ Label Encoding for nominal data
✘ OHE for high-cardinality features
✘ Fitting the encoder before train-test split

Interview Tip:
One-Hot Encoding prevents the model from assuming an artificial order between categories, making it the preferred choice for nominal variables.
```

In [ ]:
# Data encoding: Categorical features -> Numerical values

# So that model be able to understand.

In [2]:
# 1. Nominal / OHE Encoding

# Categorical feature = { Red, Green, Blue}
# After conversion
# Numerical feature:
# {1,0,0} -> for Red
# {0,1,0} -> for Green
# {0,0,1} -> for Blue

# disadvantage :

# a. for 100 categories it will introduce 100 new features
# b. Sparse matrix => Overfitting

In [6]:
# Import the pandas library and give it the short alias 'pd'.
# pandas is used for data manipulation and analysis.
# It provides the DataFrame object, which is used to store and work with tabular data
# (rows and columns, similar to an Excel spreadsheet or SQL table).
# 'as pd' is just a convention that makes the code shorter and easier to write.
import pandas as pd

# Import the OneHotEncoder class from sklearn.preprocessing.
# sklearn (Scikit-learn) is a popular machine learning library in Python.
# preprocessing is a module that contains tools for preparing data before training a model.
# OneHotEncoder is used to convert categorical (text) features into numerical format,
# because most machine learning algorithms cannot work directly with text values.
#
# Example:
# Color
# -----
# Red
# Blue
# Green
#
# becomes
#
# Color_Blue  Color_Green  Color_Red
#      0            0           1
#      1            0           0
#      0            1           0
#
# No parameters are used here because we are only importing the class,
# not creating an object yet. Parameters are provided later when writing:
# encoder = OneHotEncoder(...)
from sklearn.preprocessing import OneHotEncoder

In [7]:
# Create a pandas DataFrame (a table with rows and columns).
# pd.DataFrame() is a constructor used to create a DataFrame from data such as
# dictionaries, lists, NumPy arrays, or other tabular structures.
#
# Parameter:
# - data (passed here as a dictionary):
#   A dictionary where:
#   - Each key becomes a column name.
#   - Each value becomes the data for that column.
#   We use a dictionary because it is a simple and common way to define columns and
#   their corresponding values.

df = pd.DataFrame({

    # 'color' is the name of the column.
    # It is a categorical feature because it contains text labels instead of numbers.
    # This type of data often needs to be encoded before training a machine learning model.
    'color': [

        # Each string represents one row (one observation/sample) in the DataFrame.
        # These are the categorical values stored in the 'color' column.
        'red',
        'blue',
        'green',
        'green',
        'red',
        'blue'
    ]
})

In [8]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [10]:
# Create an instance (object) of the OneHotEncoder class.
# An instance is a usable object created from a class.
# We create this object so that we can later use its methods (such as fit(),
# transform(), or fit_transform()) to convert categorical data into numerical data.

encoder = OneHotEncoder(
    # No parameters are passed here, so OneHotEncoder uses its default settings.
    #
    # Some important default parameters are:
    #
    # categories='auto'
    # - Automatically finds all unique categories from the input data.
    # - We use the default because we don't need to manually specify the categories.
    #
    # drop=None
    # - Keeps all encoded columns.
    # - No category is removed.
    #
    # sparse_output=True
    # - Returns the encoded data as a sparse matrix by default.
    # - This saves memory when there are many categories and many zero values.
    #
    # dtype=float64
    # - The encoded values (0s and 1s) are stored as floating-point numbers.
    #
    # handle_unknown='error'
    # - Raises an error if, during transformation, it encounters a category
    #   that was not present during training (fit).
)

In [13]:
# Perform both fitting and transformation on the categorical data.
# fit_transform() is a combination of two steps:
#
# 1. fit()
#    - Learns the unique categories present in the input data.
#    - In this case, it identifies the categories:
#      ['blue', 'green', 'red']
#
# 2. transform()
#    - Converts each category into a numerical one-hot encoded format.
#    - Each category gets its own column containing 0s and 1s.
#
# Example transformation:
#
# color
# -----
# red
# blue
# green
#
# becomes:
#
# blue  green  red
#  0      0     1
#  1      0     0
#  0      1     0
#
# Parameter:
# - df[['color']]
#   - Selects the 'color' column from the DataFrame.
#   - Double square brackets are used because OneHotEncoder expects a 2D input
#     (rows and columns), not a single pandas Series.
#   - The shape of the input is:
#       (number_of_samples, number_of_features)
#       (6, 1) in this case.
#
# .toarray()
# - Converts the output from a sparse matrix into a normal NumPy array.
# - OneHotEncoder returns a sparse matrix by default because it is memory efficient.
# - Converting to an array makes the encoded values easier to view and understand.
encoded = encoder.fit_transform(df[['color']]).toarray()

In [16]:
# Import the pandas library and give it the alias 'pd'.
# pandas is used for creating and manipulating DataFrames.
import pandas as pd


# Create a new DataFrame named 'encoder_df' from the encoded data.
# A DataFrame stores data in a table format with rows and columns.
#
# Parameters:
# - encoded:
#   The input data that contains the one-hot encoded values.
#   This is usually the output returned by:
#       encoder.fit_transform(df[['color']])
#   It contains numerical 0s and 1s representing the original categories.
#
# - columns:
#   Specifies the names of the columns for the new DataFrame.
#   Here, we use encoder.get_feature_names_out() to automatically generate
#   meaningful column names from the original categorical feature.
encoder_df = pd.DataFrame(

    # The encoded numerical values that will become the DataFrame data.
    encoded,

    # Generate column names for the encoded features.
    # get_feature_names_out() returns the names of the new one-hot encoded columns.
    #
    # Example:
    # Original column:
    # color
    #
    # Generated column names:
    # color_blue
    # color_green
    # color_red
    #
    # This helps us understand which encoded column represents which category.
    columns=encoder.get_feature_names_out()
)

In [17]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [18]:
# Transform new unseen data using the already trained OneHotEncoder.
# The encoder has already learned the categories during the fit() or fit_transform() step.
# Now we only use transform() because we do not want to learn new categories again.
# We want to apply the same encoding rules to new data.

encoder.transform(

    # Provide the new categorical data that needs to be encoded.
    # The input must be 2D (rows and columns), so we use a nested list.
    #
    # [['blue']] means:
    # - One row/sample
    # - One feature/column named 'color'
    #
    # The encoder checks where "blue" belongs among the learned categories:
    # ['blue', 'green', 'red']
    # and converts it into a one-hot encoded vector.
    [['blue']]

).toarray()

# .toarray()
# - Converts the output sparse matrix into a normal NumPy array.
# - OneHotEncoder returns a sparse matrix by default because it saves memory.
# - Converting it to an array makes the encoded values easier to read.
#
# Output example:
# [[1. 0. 0.]]
#
# Meaning:
# color_blue  color_green  color_red
#     1           0            0
#
# The value 1 represents that the input category is "blue",
# while the other categories are represented as 0.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [20]:
# Concaternate the original with the new one
pd.concat([df, encoder_df], axis = 1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0